- name: Configuration of users and hosts
  hosts: archlinux
  vars:
    ansible_become: yes

  tasks:
    - name: Set hostname
      # not ansible.builtin.hostname, since the systemd way will escape the chroot
      ansible.builtin.lineinfile:
        path: /etc/hostname
        create: true
        regexp: '.*'
        line: '{{hostname}}'
      tags: hostname

    - name: Create main user
      ansible.builtin.user:
        user: '{{username}}'
        groups: wheel, uucp, video
      tags: user

    - name: Install authorized_key from localhost
      ansible.posix.authorized_key:
        user: '{{username}}'
        key: "{{ lookup('file', ssh_key_pub) }}"
        state: present
      register: authorized_keys
      tags: user

    - name: Remove Arch Linux ARM default user
      when: authorized_keys['state'] == 'present'
      ansible.builtin.user:
        name: alarm
        state: absent
        remove: yes
      tags: user
