- name: Configuration of amstan things (zsh and a bunch of other .files)
  hosts: archlinux
  tags: user_amstan

  tasks:
    - name: Install zsh
      community.general.pacman:
        package:
          - zsh
        state: present
      tags: install

    - name: Change user shell to zsh
      ansible.builtin.user:
        user: '{{username}}'
        shell: /bin/zsh

    - name: Clone .configs
      vars:
        ansible_become_user: '{{username}}'
      ansible.builtin.git:
        repo: 'https://github.com/amstan/configs.git'
        dest: '/home/{{username}}/.configs/'

    - name: Install .configs
      vars:
        ansible_become_user: '{{username}}'
      ansible.builtin.shell:
        chdir: '/home/{{username}}'
        cmd: |
          for i in .{gitconfig,gitignore,pystartup,zshrc}; do
            ln -sf .configs/$i $i
          done
        creates: '/home/{{username}}/.zshrc'
